DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (
 id INT AUTO_INCREMENT PRIMARY KEY,
 username VARCHAR(250) NOT NULL,
 password VARCHAR(250) NOT NULL,
 fullname VARCHAR(250) NOT NULL,
 age INT NOT NULL,
 dob DATE NOT NULL,
 address VARCHAR(250) NOT NULL,
 email VARCHAR(250) NOT NULL
);

